version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    # Only the workspace dependencies need updating.
    # Workspace members only use workspace dependencies.
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
