# Shorten the path in the GitHub UI.
name: coverage.yaml

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  merge_group:

# Cancel jobs for previous commits in the same branch.
# On main `head_ref` is not available and `run_id` is always unique.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  llvm-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@nightly

      - uses: ./.github/actions/setup-tools
        with:
          cargo-llvm-cov: true

      - run: |
          cargo llvm-cov --workspace --all-features --no-report
          cargo llvm-cov --doc --workspace --all-features --no-report
          cargo llvm-cov report --doctests --codecov --output-path codecov.json
          cargo llvm-cov report --doctests --json --output-path cov.json
          cargo llvm-cov report --doctests --html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            cov.json
            codecov.json
          retention-days: 1

  codecov-upload:
    runs-on: ubuntu-latest
    needs: llvm-cov
    # Skip codecov upload for dependabot PRs (no access to secrets).
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/download-artifact@v5
        with:
          name: coverage

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          disable_search: true
          files: codecov.json
